NAME	=	libft.a

SRCS	=	ft_atoi.c \
			ft_bzero.c \
			ft_calloc.c \
			ft_isalnum.c \
			ft_isalpha.c \
			ft_isascii.c \
			ft_isdigit.c \
			ft_isprint.c \
			ft_itoa.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_memset.c \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			ft_putstr_fd.c \
			ft_split.c \
			ft_strchr.c \
			ft_strdup.c \
			ft_striteri.c \
			ft_strjoin.c \
			ft_strlcat.c \
			ft_strlcpy.c \
			ft_strlen.c \
			ft_strmapi.c \
			ft_strncmp.c \
			ft_strnstr.c \
			ft_strrchr.c \
			ft_strtrim.c \
			ft_substr.c \
			ft_tolower.c \
			ft_toupper.c

OBJS	=	${SRCS:.c=.o}

SRCS_B	=	ft_lstmap.c \
			ft_lstsize.c \
			ft_lstnew.c \
			ft_lstlast.c \
			ft_lstiter.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstadd_front.c \
			ft_lstadd_back.c

OBJS_B	=	${SRCS_B:.c=.o}

CC		=	gcc
CFLAGS	=	-Werror -Wall -Wextra -I
AR		=	ar
ARFLAGS	=	-r
RM		=	rm -f

${NAME}:	${OBJS}
		${CC} ${CFLAGS} -c $^ -o $@
		${AR} ${ARFLAGS} $@
#NEED TO INCLUDE ARFLAGS
all:	${NAME}

clean:	${RM} ${OBJS}

fclean:	clean
		${RM} ${NAME}

re:		fclean all

bonus:	${OBJS_B}
		${CC} ${CFLAGS} -c $^ -o $@
		${AR} ${ARFLAGS} $@

.PHONY: all clean fclean re bonus